"""Pydantic schemas for the AI cosmic narrator."""

from pydantic import BaseModel, Field


class NarratorRequest(BaseModel):
    """User question and observation context sent to the narrator."""

    query: str = Field(..., min_length=1, max_length=1000)
    lat: float = Field(..., ge=-90, le=90)
    lon: float = Field(..., ge=-180, le=180)
    timestamp: str = Field(..., min_length=1)


class NarratorAnswer(BaseModel):
    """Plain-language answer generated by the narrator."""

    text: str
